import HeaderUnauthenticated from "@/components/organisms/HeaderUnauthenticated";
import { getDirection } from "@/helpers/getDirection";
import ClientSideProviders from "@/providers/ClientSideProviders";
import type { Metadata } from "next";
import { getSession } from "next-auth/react";
import "./globals.css";
import { Inter, Vazirmatn } from "next/font/google";

const inter = Inter({ subsets: ["latin"], display: "swap" });
const vazirmatn = Vazirmatn({ subsets: ["arabic", "latin-ext"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const session = await getSession();
  const direction = getDirection(locale);
  const fontClass = direction === "ltr" ? inter.className : vazirmatn.className;

  return (
    <html lang={locale} dir={direction}>
      <body className={fontClass}>
        <ClientSideProviders session={session!}>
          <HeaderUnauthenticated />
          {children}
        </ClientSideProviders>
      </body>
    </html>
  );
}
